server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/banking_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/banking_db
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: banking-group